apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: shashankramagentdemo
spec:
  description: Dice-rolling sample ADK-Python agent.
  modelName: us.anthropic.claude-sonnet-4-6
  modelProvider: bedrock
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-public-nonprod/dev-walkthrough/shashankram/agentdemo:v2026.7.0-37-gff8c0da4-arm64
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-shashankram
      subfolder: shashankramagentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: shashankram-arctl-init-http
