apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: daniellemustilloagentdemo-kagent
spec:
  description: Dice-rolling sample ADK-Python agent.
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-dev/dev-walkthrough/danielle-mustillo/agentdemo:v2026.8.0-54-gce2de057
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-danielle-mustillo
      subfolder: daniellemustilloagentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: danielle-mustillo-arctl-init-http-container
    - kind: MCPServer
      name: danielle-mustillo-arctl-init-stdio
    - kind: MCPServer
      name: danielle-mustillo-published-stdio-oci
    - kind: MCPServer
      name: danielle-mustillo-published-stdio-npm
    - kind: MCPServer
      name: danielle-mustillo-published-stdio-pypi
  modelProvider: bedrock
  modelName: us.anthropic.claude-sonnet-4-6
