apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: joshpritchardagentdemo
spec:
  description: Dice-rolling sample ADK-Python agent.
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-dev/dev-walkthrough/josh-pritchard/agentdemo:v2026.8.0-56-gc4473b58
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-josh-pritchard
      subfolder: joshpritchardagentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: josh-pritchard-arctl-init-http
