apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: joshpritchardagentdemo
spec:
  description: Dice-rolling sample ADK-Python agent.
  modelName: us.anthropic.claude-sonnet-4-6
  modelProvider: bedrock
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-public-nonprod/dev-walkthrough/josh-pritchard/agentdemo:v2026.5.4-26-g4661d9e7
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-josh-pritchard
      subfolder: joshpritchardagentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: josh-pritchard-everything
