apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: alanbentleypghagentdemo
spec:
  description: Dice-rolling sample ADK-Python agent.
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-dev/dev-walkthrough/alanbentleypgh/agentdemo:v2026.8.0-34-gf63ad283
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-alanbentleypgh
      subfolder: alanbentleypghagentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: alanbentleypgh-arctl-init-http
