apiVersion: ar.dev/v1alpha1
kind: Agent
metadata:
  name: xytian315agentdemo
spec:
  description: Dice-rolling sample ADK-Python agent.
  source:
    image: us-docker.pkg.dev/developers-369321/agentregistry-enterprise-dev/dev-walkthrough/xytian315/agentdemo:v2026.8.0-63-gecb97f7f9
    repository:
      url: https://github.com/solo-io/agentregistry-dev-samples.git
      branch: walkthrough-xytian315
      subfolder: xytian315agentdemo
  mcpServers:
    - kind: MCPServer
      name: test-mcp-server
    - kind: MCPServer
      name: xytian315-arctl-init-http
